function translateText() {
    let text = document.getElementById("inputText").value.trim().toLowerCase();
    let output = document.getElementById("outputText");

    const data = {
        "hello": "வணக்கம்",
        "hi": "வணக்கம்",
        "how are you": "நீங்கள் எப்படி இருக்கிறீர்கள்",
        "i am fine": "நான் நன்றாக இருக்கிறேன்",
        "what is your name": "உங்கள் பெயர் என்ன",
        "my name is": "என் பெயர்",
        "where are you from": "நீங்கள் எங்கு இருந்து வந்தீர்கள்",
        "nice to meet you": "உங்களை சந்தித்ததில் மகிழ்ச்சி",
        "good morning": "காலை வணக்கம்",
        "good evening": "மாலை வணக்கம்",
        "good night": "இரவு வணக்கம்",
        "thank you": "நன்றி",
        "thanks": "நன்றி",
        "sorry": "மன்னிக்கவும்",
        "please help me": "தயவு செய்து உதவுங்கள்",
        "can you help me": "நீங்கள் எனக்கு உதவ முடியுமா",
        "what are you doing": "நீங்கள் என்ன செய்கிறீர்கள்",
        "i am working": "நான் வேலை செய்கிறேன்",
        "i am studying": "நான் படிக்கிறேன்",
        "do you understand": "நீங்கள் புரிந்துகொள்கிறீர்களா",
        "yes i understand": "ஆம் நான் புரிந்துகொள்கிறேன்",
        "no i dont understand": "இல்லை நான் புரிந்துகொள்ளவில்லை",
        "where is the bus stop": "பஸ் நிறுத்தம் எங்கே",
        "where is the hospital": "மருத்துவமனை எங்கே",
        "where is the school": "பள்ளி எங்கே",
        "what time is it": "இப்போது நேரம் என்ன",
        "come here": "இங்கே வாருங்கள்",
        "go there": "அங்கே போங்கள்",
        "wait here": "இங்கே காத்திருங்கள்",
        "sit down": "உட்காருங்கள்",
        "stand up": "நிற்கவும்",
        "open the door": "கதவை திறக்கவும்",
        "close the door": "கதவை மூடவும்",
        "give me water": "எனக்கு தண்ணீர் கொடுக்கவும்",
        "i am hungry": "எனக்கு பசிக்கிறது",
        "i am tired": "நான் சோர்வாக இருக்கிறேன்",
        "i am happy": "நான் மகிழ்ச்சியாக இருக்கிறேன்",
        "i am sad": "நான் சோகமாக இருக்கிறேன்",
        "good job": "நல்ல வேலை",
        "congratulations": "வாழ்த்துகள்",
        "welcome": "வரவேற்கிறோம்",
        "see you later": "பிறகு சந்திப்போம்",
        "take care": "கவனமாக இருங்கள்",
        "call me": "என்னை அழைக்கவும்",
        "message me": "எனக்கு மெசேஜ் அனுப்புங்கள்",
        "i will come later": "நான் பிறகு வருவேன்",
        "i will call you": "நான் உங்களை அழைப்பேன்",
        "dont worry": "கவலைப்படாதீர்கள்",
        "be careful": "கவனமாக இருங்கள்",
        "keep going": "தொடர்ந்து செல்லுங்கள்",
        "stop here": "இங்கே நிறுத்துங்கள்",
        "start now": "இப்போது தொடங்குங்கள்",
        "finish this": "இதனை முடிக்கவும்",
        "listen to me": "என்னை கேளுங்கள்",
        "look here": "இங்கே பாருங்கள்",
        "tell me": "எனக்கு சொல்லுங்கள்",
        "show me": "எனக்கு காட்டுங்கள்",
        "help me please": "தயவு செய்து உதவுங்கள்",
        "i need help": "எனக்கு உதவி தேவை",
        "i am ready": "நான் தயாராக இருக்கிறேன்",
        "are you ready": "நீங்கள் தயாரா",
        "lets go": "வாங்க போகலாம்",
        "come fast": "விரைவாக வாருங்கள்",
        "go fast": "விரைவாக போங்கள்",
        "slow down": "மெதுவாக செல்லுங்கள்",
        "be quiet": "அமைதியாக இருங்கள்",
        "speak slowly": "மெதுவாக பேசுங்கள்",
        "i like this": "எனக்கு இது பிடிக்கும்",
        "i dont like this": "எனக்கு இது பிடிக்கவில்லை",
        "this is good": "இது நல்லது",
        "this is bad": "இது மோசம்",
        "very good": "மிகவும் நல்லது",
        "very bad": "மிகவும் மோசம்",
        "see this": "இதைக் பாருங்கள்",
        "try again": "மீண்டும் முயற்சிக்கவும்",
        "well done": "நன்றாக செய்தீர்கள்",
        "excellent": "அருமை",
        "perfect": "சரியானது"
    };

    output.innerText = data[text] || "Sentence not found";
}